#pragma once

#define TRAMPOLINE_PHYSICAL_ADDRESS 0x7000

#define AP_STACK_SIZE (1 * 1024 * 1024)
#define AP_STACK_ALIGNMENT 16

#define IA32_GS_BASE 0xC0000101u

#define SMP_OFFSET_GDTR      0xF10
#define SMP_OFFSET_FAR32     0xF00
#define SMP_OFFSET_FAR64     0xF08
#define SMP_OFFSET_GDT       0xF20
#define SMP_OFFSET_CR3       0xF60
#define SMP_OFFSET_STACK     0xF68
#define SMP_OFFSET_CORE_INFO 0xF70
#define SMP_OFFSET_ENTRY     0xF78
#define SMP_OFFSET_CPU_INDEX 0xF80

#define SMP_BREADCRUMB_OKAY_VALUE 67

#define SMP_BREADCRUMB_ENTRY   0xF88
#define SMP_BREADCRUMB_GDTR    0xF89
#define SMP_BREADCRUMB_PE      0xF8A
#define SMP_BREADCRUMB_PM32    0xF8B
#define SMP_BREADCRUMB_CR3     0xF8C
#define SMP_BREADCRUMB_LME     0xF8D
#define SMP_BREADCRUMB_PG      0xF8E
#define SMP_BREADCRUMB_LM64    0xF8F
#define SMP_BREADCRUMB_STACK   0xF90
#define SMP_BREADCRUMB_GS      0xF91
#define SMP_BREADCRUMB_ENTRY64 0xF92

#define SMP_SEGMENT_OFFSET_IN_GDT_PM32_CODE 0x08
#define SMP_SEGMENT_OFFSET_IN_GDT_PM32_DATA 0x10
#define SMP_SEGMENT_OFFSET_IN_GDT_LM64_CODE 0x20

#define CONTEXT_SWITCH_OFFSET_RBX 0
#define CONTEXT_SWITCH_OFFSET_RBP 8
#define CONTEXT_SWITCH_OFFSET_R12 16
#define CONTEXT_SWITCH_OFFSET_R13 24
#define CONTEXT_SWITCH_OFFSET_R14 32
#define CONTEXT_SWITCH_OFFSET_R15 40
#define CONTEXT_SWITCH_OFFSET_RSP 48
#define CONTEXT_SWITCH_OFFSET_RIP 56

#define THREAD_MAX_COUNT 64
#define THREAD_STACK_SIZE (64 * 1024)
